FROM ubuntu
USER root
ENV DEBIAN_FRONTEND noninteractive
RUN apt update && apt dist-upgrade -y
RUN apt install -y mc wget telnet git curl iotop atop
RUN mkdir /install
WORKDIR /install
RUN echo 1
RUN echo 2.6.5
RUN wget https://bitcoincore.org/bin/bitcoin-core-22.0/bitcoin-22.0-x86_64-linux-gnu.tar.gz
RUN wget https://bitcoincore.org/bin/bitcoin-core-22.0/SHA256SUMS && sha256sum --ignore-missing --check SHA256SUMS
RUN tar -xf bitcoin-22.0-x86_64-linux-gnu.tar.gz
RUN mkdir /app
RUN mv bitcoin-22.0/* /app/
WORKDIR /app

#RUN gpg --verify algorand-indexer_2.6.5_amd64.deb.sig algorand-indexer_2.6.5_amd64.deb
COPY . . 
RUN useradd -ms /bin/bash -d /home/btc btc
RUN chown btc:btc /app -R
RUN chown btc:btc /home/btc -R
USER btc
ENV PATH="/app/bin:${PATH}"
CMD ["/bin/bash"]


