kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: bitcoincore-ss
  namespace: bitcoincore-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bitcoincore-app-ss
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: bitcoincore-app-ss
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - bitcoincore-app-ss
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: bitcoincore-pod-test
          image: scholtz2/bitcoincore:22.0-stable
          command: ["/bin/bash"]  
          args: ["-c", "./run.sh"]
#          command:
#            - /bin/bash
#            - '-c'
#            - '--'
#          args:
#            - while true; do sleep 30; done;
          resources:
            requests:
              memory: "10000Mi"
              cpu: "6000m"
            limits:
              memory: "12000Mi"
              cpu: "8000m"
          ports:
            - containerPort: 18332
              protocol: TCP
#          startupProbe:
#            tcpSocket:
#              port: 18332
#            initialDelaySeconds: 60
#            periodSeconds: 10   
#            failureThreshold: 100
#          readinessProbe:
#            tcpSocket:
#              port: 18332
#            initialDelaySeconds: 60
#            timeoutSeconds: 10   
#            failureThreshold: 100
#          livenessProbe:
#            tcpSocket:
#              port: 18332
#            initialDelaySeconds: 60
#            timeoutSeconds: 10        
#            failureThreshold: 6
          resources: {}
          volumeMounts:
            - name: bitcoincore-vol-test
              mountPath: /home/btc/.bitcoin
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      schedulerName: default-scheduler
  volumeClaimTemplates:
    - kind: PersistentVolumeClaim
      apiVersion: v1
      metadata:
        name: bitcoincore-vol-test
        namespace: bitcoincore-test
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 600Gi
        storageClassName: btcdatadir-test
        volumeMode: Filesystem
  serviceName: btc-set-service-ss
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-pv-btcdatadir-test
spec:
  storageClassName: btcdatadir-test
  capacity:
    storage: 600Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/run/desktop/mnt/host/d/algo/btc/data-test"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - docker-desktop